on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  publish:
    name: Publish Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: dist/.cache
          key: cache-dist
      - uses: oven-sh/setup-bun@v1
      - name: Setup Navi
        run: |
          ./public/install nightly
      - name: Build Website
        run: |
          navi doc --stdlib -o stdlib.json
          navi run script/generate-release.nv
          navi run script/generate-stdlib.nv
          bun install
          bun run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.vitepress/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
