on:
  push:
    branches:
      - main
      - fix-ci
  schedule:
    - cron: "0 0 * * 0"
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    name: Publish Website
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: dist/.cache
          key: cache-dist
      - uses: oven-sh/setup-bun@v1
      - name: Setup Navi
        run: |
          ./public/install nightly
          echo "$HOME/.navi" >> $GITHUB_PATH
      - name: Build Website
        run: |
          navi doc ~/.navi/stdlib -o stdlib.json --include-native
          navi doc ~/.navi/pkg -o pkg.json --include-native
          bun install
          bun run build
      - name: Upload stdlib.json & pkg.json
        uses: actions/upload-artifact@v4
        with:
          path: |
            stdlib.json
            pkg.json
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ".vitepress/dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
