on:
  push:

jobs:
  test:
    name: Test Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: dist/.cache
          key: cache-dist
      - uses: oven-sh/setup-bun@v1
      - uses: navi-language/setup-navi@v1
        with:
          navi-version: nightly
      - run: |
          navi doc ~/.navi/stdlib -o stdlib.json --include-native
          navi doc ~/.navi/pkg -o pkg.json --include-native
          bun run test:all
  test_install:
    name: Test Install Navi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ./public/install
          ./public/install nightly
