on:
  push:

jobs:
  test:
    name: Publish Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: dist/.cache
          key: cache-dist
      - uses: oven-sh/setup-bun@v1
      - run: |
          bun install
          bun test
